"""
Judge network: scores sequences to express a quality preference.

This file exists to define the judge — the model whose learned preferences
drive policy training. The judge starts partially aligned with q* (Spearman
~0.7) and is then updated each iteration on pairs generated by the current
policy, labelled by its own current preferences.

This feedback loop is what causes alignment drift: the judge's training
distribution narrows to wherever the policy currently puts mass, gradually
decoupling judge scores from ground-truth quality. The diagnostics layer
measures this decoupling by comparing J(x) against q*(x) over the full
output space.

Architecture: token embedding -> 1-layer GRU -> final hidden state ->
linear projection to a scalar. Around 5K parameters.
"""

import flax.linen as nn
import jax.numpy as jnp

from coevolution.config import AgentConfig, WorldConfig


class Judge(nn.Module):
    """Sequence scorer that maps a token sequence to an unbounded scalar.

    The scalar is interpreted as a quality score: higher means the judge
    considers the sequence better. Preferences between pairs are derived
    via sigmoid(J(x_a) - J(x_b)).

    Attributes:
        cfg: Architecture hyperparameters (embed_dim, hidden_dim).
        world: World configuration (vocab_size, seq_len).
    """

    cfg: AgentConfig
    world: WorldConfig

    @nn.compact
    def __call__(self, x: jnp.ndarray) -> jnp.ndarray:
        """Score a batch of sequences.

        Reads the full sequence left-to-right through a GRU and projects
        the final hidden state to a scalar. The final hidden state is used
        rather than pooling because it captures sequential context —
        a judge that only saw token frequencies could not detect the
        compositional interactions that make q* non-trivial.

        Args:
            x: Integer token array of shape (batch, seq_len) with values
               in [0, vocab_size).

        Returns:
            Float array of shape (batch,) — unbounded scalar quality scores.
        """
        B, L = x.shape
        embedded = nn.Embed(
            self.world.vocab_size, self.cfg.embed_dim, name="embed"
        )(x)  # (B, L, embed_dim)

        gru = nn.GRUCell(self.cfg.hidden_dim, name="gru")
        h = jnp.zeros((B, self.cfg.hidden_dim))

        for t in range(L):
            h, _ = gru(h, embedded[:, t])

        # Project the final hidden state to a single quality score
        scores = nn.Dense(1, name="proj")(h)  # (B, 1)
        return scores.squeeze(-1)  # (B,)
