"""
Judge network: scores sequences to express a quality preference.

This file exists to define the judge — the model whose learned preferences drive
policy training. The judge starts partially aligned with q* (Spearman ~0.7) and
is then updated on pairs generated by the current policy, labelled by its own
current preferences. This feedback loop is what causes alignment drift: the
judge's training distribution narrows to wherever the policy currently puts
mass, gradually decoupling judge scores from ground-truth quality.

Architecture: token embedding -> 1-layer GRU -> final hidden state ->
linear projection to a scalar score. Around 5K parameters.
"""

# TODO: Milestone 2
